## MDB generated config template
[server]
bind-address=":8080"
mode="debug"  # GIN mode. Either debug, release or test
rollbar-token=""
rollbar-environment="development"

[mdb]
url="postgres://postgres/mdb?sslmode=disable&user=postgres&password=test123"

[kmedia_old]
url="postgres://postgres/mdb?sslmode=disable&user=postgres&password=test123"

[test]
url-template="postgres://postgres/%s?sslmode=disable&user=postgres&password=test123"
debug-sql=false

[storage]
api-url="http://storage.backend.com"
index-directory="/somewhere/to/store/index/files/"

[nats]
url="nats://localhost:4222"
pub-ack-wait="30s"
client-id="my-sample-nats-client"
cluster-id="my-nats-cluster-id"
subject="subject"

[events]
handlers=["logger"]
emitter-size=1024

[authentication]
enable=true
issuer="https://accounts.kbb1.com/auth/realms/main"

[permissions]
enable=true
log=true
